### PR TITLE
Add generic list types

### LINKED ISSUE #19: Add generic list types
## Is your feature request related to a problem? Please describe

Some of the list like properties have typehints such as `Facets|Facet[]`, while these are helpful I think it would be more beneficial to use the generic types such as `ArrayList<Facet>`.

Thanks for the module, I think its great ❤️ 

## Describe the solution you'd like

Updating the list types to use generic ones provided in Silverstripe 5.2

## Describe alternatives you've considered

The current alternative is to leave as is.

## Additional context

This would require bumping the minimum `silverstripe/framework` to 5.2

### PR DESCRIPTION
**Pull request by Cambis**
Resolves #19

### CODE REVIEW

**Comment by chrispenny** [comment]
Thank you for the contribution! I wasn't aware of that `@extends` paradigm, that's really cool.

Framework 5.1 is OEL very soon (Oct 17th), so I'll come back to this then. I'll prob need to update the other integration modules at the same time.

**Comment by chrispenny** [comment]
@Cambis is the framework minimum requirement actually needed for these code hints?

If not, I'd maybe suggest that we just drop that bit.

**Comment by Cambis** [comment]
@chrispenny in order for them to work yes, but since they are just phpdoc they won't break if the version is 5.1

Happy to drop the requirement :)

**Comment by chrispenny** [comment]
Thanks, @Cambis. All good, let's keep the version bump.

It's all working for me - just waiting for the 17th before I merge/tag.

**Comment by Cambis** [comment]
Sweet thanks @chrispenny 🎉

**Comment by chrispenny** [comment]
One day early sure be fine....

New tag incoming!

**Pull request merged**
